project:
  type: website
  output-dir: docs

website:
  title: "BIOL B215: Biostatistics with R"
  site-url: https://github.com/bbitarello/b215f2025
  repo-url: https://github.com/bbitarello/b215f2025
  repo-branch: main
  repo-actions: [source]
  sidebar:
    background: primary
    logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/bbitarello/b215f2025
        text: GitHub
    style: docked
    contents:
    - href: index.qmd
      text: Home
    - href: slides.qmd
      text: Slides
    - href: psets.qmd
      text: Problem Sets
    - href: syllabus.qmd
      text: Syllabus
    - href: final-project.qmd
      text: Final Project
    
format:
  html:
    theme: 
     - journal
     - style.css
    toc: true


editor: source