---
title: "BIOL B215: Biostatistics with R"
---

# Course Information

-   Instructor: Bárbara D. Bitarello (bbitarello \[at\] brynmawr.edu)
-   TA: Nicole Cavalieri (ncavalieri \[at\] brynmawr.edu)
-   Lecture: Monday & Wednesday 11:40 AM (Park 264)
-   Lab: Wednesday 1:10 - 4 PM
-   Remember to read the [syllabus](syllabus.qmd), [listen to Snoop Dog](https://www.youtube.com/embed/aL_fP5axQV4).
-   Lecture notes:
-   [Piazza (for Qs)](https://piazza.com/brynmawr/fall2025/bmcbiolb215001f25)
-   [Moodle](https://moodle.brynmawr.edu/course/view.php?id=8224)
-   [Rstudio (Posit) Cloud](https://posit.cloud/spaces/678147/join?access_code=hl0WMhTu8LNwvW1hn-uIdm_lx1Xm8sCjIUMwCW24)
-   Remember to read the [Course Info](syllabus.qmd), [listen to SD](https://www.youtube.com/embed/aL_fP5axQV4).

## Lectures

Lecture slides, class notes, and problem sets are linked below. New material is added approximately on a weekly basis.

| Dates | Topic | Slides | Reading |
|:------|:------|:-------|:--------|

## Problem sets

| Problem set | Topic | Due Date | Difficulty |
|:------------|:------|:---------|:-----------|
| 1           |       | Week 4   |            |
| 2           |       |          |            |
| 3           |       |          |            |
| 4           |       |          |            |
| 5           |       |          |            |

## Lab Assignments

| Lab assignment | Topics | Due Date | Difficulty |
|:---------------|:-------|:---------|:-----------|
| 1              |        |          |            |
| 2              |        |          |            |

## Midterms & Coding Interview

| Assessment       | Topics           | When/Where        | Difficulty |
|:-----------------|:-----------------|:------------------|:-----------|
| Midterm 1        | Week 1-7         | 10/28, during lab | Hard       |
| Midterm 2        | Weeks 1-14       | Finals week, TBD  | Hard       |


## Office hour times

| Who                     | When            | Where            |
|-------------------------|-----------------|------------------|
| Professor drop-in hours | Tuesday 3-4pm   | Park 211 or zoom |
| Professor drop-in hours | Wednesday 2-3pm | Park 211 or zoom |
| Professor drop-in hours | Friday 2-3pm    | Park 211 or zoom |
| TA                      | TBD by survey   | TBD              |

## Acknowledgments

We thank [Maria Tackett](https://github.com/matackett) and [Mine Çetinkaya-Rundel](https://github.com/mine-cetinkaya-rundel) for sharing their [web page template](https://github.com/rstudio-conf-2022/teach-ds-course-website/tree/main) which we used in creating this website, and [Rafael Irizarry](https://github.com/rafalab) sharing this template. We also thank [Yaniv Brandvain](https://brandvainlab.wordpress.com/) for sharing awesome teaching materials. Thank you also to [fbriatte.org](https://f.briatte.org/r/asking-r-questions) for curating so many useful tips shared with students in [R links](docs/learnr.html).
